Add stage to deploy release docs to simpeg-doctest

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -238,3 +238,90 @@ stages:
           displayName: Push documentation to simpeg-doctest
           env:
             GH_TOKEN: $(gh.token)
+
+- stage: Deploy release docs to simpeg-doctest (experimental)
+  dependsOn: Testing
+  condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
+  jobs:
+    - job:
+      displayName: Deploy docs to simpeg-doctest (experimental)
+      pool:
+        vmImage: ubuntu-latest
+      variables:
+        python.version: '3.8'
+      timeoutInMinutes: 240
+      steps:
+        - script: |
+            git config --global user.name ${GH_NAME}
+            git config --global user.email ${GH_EMAIL}
+            git config --list | grep user.
+          displayName: 'Configure git'
+          env:
+            GH_NAME: $(gh.name)
+            GH_EMAIL: $(gh.email)
+
+        - script: |
+            wget -O Mambaforge.sh  "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
+            bash Mambaforge.sh -b -p "${HOME}/conda"
+          displayName: Install mamba
+
+        - script: |
+            source "${HOME}/conda/etc/profile.d/conda.sh"
+            source "${HOME}/conda/etc/profile.d/mamba.sh"
+            cp environment_test.yml environment_test_with_pyversion.yml
+            echo "  - python="$(python.version) >> environment_test_with_pyversion.yml
+            mamba env create -f environment_test_with_pyversion.yml
+            rm environment_test_with_pyversion.yml
+            conda activate simpeg-test
+            pip install pytest-azurepipelines
+          displayName: Create Anaconda testing environment
+
+        - script: |
+            source "${HOME}/conda/etc/profile.d/conda.sh"
+            conda activate simpeg-test
+            pip install -e .
+          displayName: Build package
+
+        - script: |
+            source "${HOME}/conda/etc/profile.d/conda.sh"
+            conda activate simpeg-test
+            export KMP_WARNINGS=0
+            make -C docs html
+          displayName: Building documentation
+
+        # Upload dev build of the docs to gh-pages branch in simpeg/simpeg-docs
+        - script: |
+            # Capture version
+            # TODO: we should be able to get the version from the
+            # build.sourceBranch variable
+            version=$(git tag --points-at HEAD)
+            if [ -n "$version" ]; then
+              echo "Version could not be obtained from tag. Exiting."
+              exit 1
+            fi
+            # Capture hash of last commit in simpeg
+            commit=$(git rev-parse --short HEAD)
+            # Clone the repo where we store the documentation
+            git clone --depth 1 https://${GH_TOKEN}@github.com/simpeg/simpeg-doctest.git
+            cd simpeg-doctest
+            # Move the built docs to a new dev folder
+            mv $BUILD_SOURCESDIRECTORY/docs/_build/html "$version"
+            cp $BUILD_SOURCESDIRECTORY/docs/README.md .
+            # Add .nojekyll if missing
+            touch .nojekyll
+            # Update latest symlink
+            rm -f latest
+            ln -s "$version" latest
+            # Commit the new docs.
+            git add "$version" README.md .nojekyll latest
+            message="Azure CI deploy ${version} from ${commit}"
+            echo -e "\nMaking a new commit:"
+            git commit -m "$message"
+            # Make the push quiet just in case there is anything that could
+            # leak sensitive information.
+            echo -e "\nPushing changes to simpeg/simpeg-doctest."
+            git push -fq origin gh-pages 2>&1 >/dev/null
+            echo -e "\nFinished uploading generated files."
+          displayName: Push documentation to simpeg-doctest
+          env:
+            GH_TOKEN: $(gh.token)
